services:
  - type: web
    name: myshop
    env: python
    buildCommand: cd myshop && pip install -r requirements.txt
    startCommand: cd myshop && gunicorn myshop.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
