services:
  - type: web
    name: myshop
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myshop.myshop.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
